import fs from 'fs';
import path from 'path';
import { writeFileEnsured } from './fs-utils.js';

export function initProject(dir, options = {}) {
  fs.mkdirSync(dir, { recursive: true });

  const contentPath = path.join(dir, 'content', 'site.yaml');
  const configPath = path.join(dir, 'sitegen.config.json');

  if (!fs.existsSync(contentPath)) {
    writeFileEnsured(contentPath, sampleSiteYaml());
  }

  if (!fs.existsSync(configPath)) {
    writeFileEnsured(configPath, `${JSON.stringify({
      template: options.template || './template',
      content: './content/site.yaml',
      output: './site',
    }, null, 2)}\n`);
  }

  return { dir, contentPath, configPath };
}

export function createTemplate(dir) {
  fs.mkdirSync(dir, { recursive: true });

  writeFileEnsured(path.join(dir, 'sitegen.template.json'), `${JSON.stringify({
    name: path.basename(dir),
    description: 'Custom sitegen template',
    templateDir: 'template',
  }, null, 2)}\n`);

  writeFileEnsured(path.join(dir, 'template', 'package.json'), `${JSON.stringify({
    name: path.basename(dir),
    type: 'module',
    scripts: {
      dev: 'astro dev',
      build: 'astro build',
      preview: 'astro preview',
    },
    dependencies: {
      astro: '^5.0.0',
    },
  }, null, 2)}\n`);

  writeFileEnsured(path.join(dir, 'template', 'astro.config.mjs'), "import { defineConfig } from 'astro/config';\n\nexport default defineConfig({});\n");
  writeFileEnsured(path.join(dir, 'template', 'src', 'layouts', 'BaseLayout.astro'), baseLayout());
  writeFileEnsured(path.join(dir, 'template', 'src', 'components', 'Hero.astro'), heroComponent());
  writeFileEnsured(path.join(dir, 'template', 'src', 'pages', '.gitkeep'), '');

  return { dir };
}

function sampleSiteYaml() {
  return `site:
  name: "Example Site"
  tagline: "Generated from YAML"
  logo:
    text: "Example"

navigation:
  navbar:
    links:
      - { label: "Home", href: "/" }
    cta: { label: "Start", href: "/" }
  footer:
    brand:
      tagline: "Generated from YAML"
    columns: []
    bottom:
      copyright: "Example Site"
      links: []

pages:
  - slug: ""
    title: "Example Site"
    sections:
      - type: hero
        heading: "Build from content"
        subheading: "This page was generated by agent-sitegen."
`;
}

function baseLayout() {
  return `---
const { title, site, navigation } = Astro.props;
---
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{title}</title>
  </head>
  <body>
    <main>
      <slot />
    </main>
  </body>
</html>
`;
}

function heroComponent() {
  return `---
/**
 * @sitegen component
 * type: hero
 * name: Hero
 * description: Simple hero section with a heading and subheading.
 * group: Hero Sections
 * props:
 *   heading:
 *     type: string
 *     required: true
 *   subheading:
 *     type: string
 *     required: false
 */
const { heading, subheading } = Astro.props;
---
<section>
  <h1>{heading}</h1>
  {subheading && <p>{subheading}</p>}
</section>
`;
}
